language: java
services:
  - mysql
before_install:
  - mysql  -u root -e 'CREATE DATABASE IF NOT EXISTS hibernate_crud;'
  - mysql  -u root -p "UPDATE user SET authentication_string=password('root') WHERE user='root';"